In [1]:
import pandas as pd

In [2]:
cases = list(range(1,9))     # cria uma lista de 1 até n+1 do número de casos exportados
points_lengh = 30            # quantidade de pontos que foram exportados em cada caso

In [3]:
df = pd.read_csv("data\export-transient.csv")  # importa o arquivo csv gerado no cfd-post

In [4]:
df

             X        Y          Z    Mass_Fraction
0     9.741232 -2.606449  -8.497672        0.000163
1     9.741232 -2.606449  -3.745275        0.009198
2     9.741232 -2.606449   1.007125        0.000101
3     9.741232 -2.606449   5.759521        0.000997
4     9.741232 -2.606449  10.511920        0.000246
..         ...       ...        ...             ...
235 -14.020760 -2.606449  -8.497672        0.006123
236 -14.020760 -2.606449  -3.745275        0.000624
237 -14.020760 -2.606449   1.007125        0.006479
238 -14.020760 -2.606449   5.759521        0.000641
239 -14.020760 -2.606449  10.511920        0.008641

[240 rows x 4 columns]

In [18]:
case_number = []             # cria lista vazia
point_number = []            # cria lista vazia
for case in cases:           # percorre a lista com número de casos definido
    i=0 
    while i < points_lengh:           # enquanto i é menor do que o número de possíveil pontos de detecção exportados
        case_number.append('Case_{}'.format(case))    # nomeia os Casos a cada n total de pontos
        point_number.append('Point_{}'.format(i+1))   # nomeia os pontos de 1 a n para cada caso
        i += 1

In [6]:
case_number   # para verificar se está correto

['Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_1',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_2',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_3',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_4',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_5',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_6',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_7',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8',
 'Case_8']

In [7]:
points = list(set(point_number))    # cria a lista de pontos sem repetição para usar adiante
points                              # para verificar se está correto

['Point_13',
 'Point_4',
 'Point_25',
 'Point_22',
 'Point_27',
 'Point_14',
 'Point_11',
 'Point_1',
 'Point_20',
 'Point_29',
 'Point_19',
 'Point_30',
 'Point_8',
 'Point_12',
 'Point_3',
 'Point_17',
 'Point_26',
 'Point_16',
 'Point_2',
 'Point_6',
 'Point_28',
 'Point_7',
 'Point_5',
 'Point_23',
 'Point_15',
 'Point_9',
 'Point_24',
 'Point_10',
 'Point_18',
 'Point_21']

In [8]:
df['Case_Number'] = case_number     # acrescenta a coluna com o número de cada caso
df['Point_Number'] = point_number   # acrescenta a coluna com o número de cada ponto
df

             X        Y          Z    Mass_Fraction Case_Number Point_Number
0     9.741232 -2.606449  -8.497672        0.000163      Case_1      Point_1
1     9.741232 -2.606449  -3.745275        0.009198      Case_1      Point_2
2     9.741232 -2.606449   1.007125        0.000101      Case_1      Point_3
3     9.741232 -2.606449   5.759521        0.000997      Case_1      Point_4
4     9.741232 -2.606449  10.511920        0.000246      Case_1      Point_5
..         ...       ...        ...             ...         ...          ...
235 -14.020760 -2.606449  -8.497672        0.006123      Case_8     Point_26
236 -14.020760 -2.606449  -3.745275        0.000624      Case_8     Point_27
237 -14.020760 -2.606449   1.007125        0.006479      Case_8     Point_28
238 -14.020760 -2.606449   5.759521        0.000641      Case_8     Point_29
239 -14.020760 -2.606449  10.511920        0.008641      Case_8     Point_30

[240 rows x 6 columns]

In [9]:
df['Detected'] = 0 # acrescenta uma coluna vazia
df.head(31)     # imprime para conferência

,X,Y,Z,Mass_Fraction,Case_Number,Point_Number,Detected
0,9.741232,-2.606449,-8.497672,0.000163,Case_1,Point_1,0
1,9.741232,-2.606449,-3.745275,0.009198,Case_1,Point_2,0
2,9.741232,-2.606449,1.007125,0.000101,Case_1,Point_3,0
3,9.741232,-2.606449,5.759521,0.000997,Case_1,Point_4,0
4,9.741232,-2.606449,10.511920,0.000246,Case_1,Point_5,0
5,4.988835,-2.606449,-8.497672,0.000842,Case_1,Point_6,0
6,4.988835,-2.606449,-3.745275,0.008786,Case_1,Point_7,0
7,4.988835,-2.606449,1.007125,0.000891,Case_1,Point_8,0
8,4.988835,-2.606449,5.759521,0.000933,Case_1,Point_9,0
9,4.988835,-2.606449,10.511920,0.000137,Case_1,Point_10,0
10,0.236435,-2.606449,-8.497672,0.000787,Case_1,Point_11,0
11,0.236435,-2.606449,-3.745275,0.007918,Case_1,Point_12,0
12,0.236435,-2.606449,1.007125,0.007504,Case_1,Point_13,0
13,0.236435,-2.606449,5.759521,0.008107,Case_1,Point_14,0
14,0.236435,-2.606449,10.511920,0.000871,Case_1,Point_15,0
15,-4.515960,-2.606449,-8.497672,0.000720,Case_1,Point_16,0
16,-4.515960,-2.606449,-3.745275,0.000714,Case_1,Point_17,0
17,-4.515960,-2.606449,1.007125,0.006895,Case_1,Point_18,0
18,-4.515960,-2.606449,5.759521,0.007129,Case_1,Point_19,0
19,-4.515960,-2.606449,10.511920,0.000836,Case_1,Point_20,0
20,-9.268360,-2.606449,-8.497672,0.006603,Case_1,Point_21,0
21,-9.268360,-2.606449,-3.745275,0.006590,Case_1,Point_22,0
22,-9.268360,-2.606449,1.007125,0.000666,Case_1,Point_23,0
23,-9.268360,-2.606449,5.759521,0.000666,Case_1,Point_24,0
24,-9.268360,-2.606449,10.511920,0.009042,Case_1,Point_25,0
25,-14.020760,-2.606449,-8.497672,0.006123,Case_1,Point_26,0
26,-14.020760,-2.606449,-3.745275,0.000624,Case_1,Point_27,0
27,-14.020760,-2.606449,1.007125,0.006479,Case_1,Point_28,0
28,-14.020760,-2.606449,5.759521,0.000641,Case_1,Point_29,0
29,-14.020760,-2.606449,10.511920,0.008641,Case_1,Point_30,0
30,9.741232,-2.606449,-8.497672,0.000319,Case_2,Point_1,0

In [10]:
df2 = df.copy()                                     # cria um novo df igual ao anterior
df2.loc[df2.iloc[:, 3] <= 0.002, 'Detected'] = 0    # na coluna Detected escreverá 0 para fração mássica não detectável e 1 para fração mássica detectável
df2.loc[df2.iloc[:, 3] > 0.002, 'Detected'] = 1   
df2

,X,Y,Z,Mass_Fraction,Case_Number,Point_Number,Detected
0,9.741232,-2.606449,-8.497672,0.000163,Case_1,Point_1,0
1,9.741232,-2.606449,-3.745275,0.009198,Case_1,Point_2,1
2,9.741232,-2.606449,1.007125,0.000101,Case_1,Point_3,0
3,9.741232,-2.606449,5.759521,0.000997,Case_1,Point_4,0
4,9.741232,-2.606449,10.511920,0.000246,Case_1,Point_5,0
...,...,...,...,...,...,...,...
235,-14.020760,-2.606449,-8.497672,0.006123,Case_8,Point_26,1
236,-14.020760,-2.606449,-3.745275,0.000624,Case_8,Point_27,0
237,-14.020760,-2.606449,1.007125,0.006479,Case_8,Point_28,1
238,-14.020760,-2.606449,5.759521,0.000641,Case_8,Point_29,0
239,-14.020760,-2.606449,10.511920,0.008641,Case_8,Point_30,1

In [13]:
df2[['Point_Number', 'Detected']].groupby('Point_Number').agg(lambda x: list(set(x))).Detected.value_counts().reset_index()  
# mostrar a quantidade de pontos que não detectaram nenhum caso, ou seja, tem o index [0]

    index  Detected
0  [0, 1]        27
1     [0]         3

In [17]:
pcd = []                                                    # cria um dicionário com as informações de ponto, caso e detecção.
final_df = pd.DataFrame()                                   # para a geração do df a partir do dicionário.
for i in points:                                            # caminha cada item da lista points (lista com o nome dos n pontos).
    dfa = df2[df2["Point_Number"] == i]                     # cria um df, a partir do df completo, onde Point_Number é um "Point_i").
    dfb = dfa[dfa["Detected"] == 1]                         # cria um df, a partir do df completo, onde só os casos detectados são escritos.
    lista_dentro = list(dfb["Case_Number"])                 # cria uma lista com a informação dos Case_Number apenas que foram detectados.
    item_pcd = {                            
            "Casos identificados": lista_dentro,            # cria o dicionário item_pcd que contém,
            "Quantidade": len(lista_dentro),                # para cada ponto (que teve pelo menos detecção de um caso), a quantidade e identificação dos casos detectados.
            "Point": i                                      
        }
    final_df = final_df.append(pd.DataFrame(item_pcd))      # cria um df final a partir do dicionário item_pcd.

final_df.sort_values(["Quantidade"], ascending=False)       # ordena o df final por ordem decrescente de quantidade de casos que foram detectados.

   Casos identificados  Quantidade     Point
0               Case_2           7   Point_3
3               Case_4           7  Point_12
1               Case_3           7  Point_10
0               Case_2           7  Point_10
6               Case_8           7   Point_3
..                 ...         ...       ...
1               Case_8           2   Point_5
0               Case_3           2  Point_29
1               Case_4           2  Point_29
0               Case_2           2  Point_16
0               Case_4           2   Point_5

[121 rows x 3 columns]